# Generated by Django 3.0.3 on 2020-02-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpsls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Cerrado'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nick_name',
            field=models.CharField(max_length=30, verbose_name='Ápodo'),
        ),
    ]
