# Generated by Django 3.0.3 on 2020-02-22 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpsls', '0002_auto_20200221_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultgame',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='rpsls.Player'),
        ),
    ]
