# Generated by Django 3.0.3 on 2020-02-22 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpsls', '0007_auto_20200222_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='oponent',
        ),
        migrations.AddField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='rpsls.Player'),
        ),
    ]
